# Sử dụng PHP 8.1 FPM với Alpine Linux để tối ưu
FROM php:8.2-fpm

# Thiết lập thư mục làm việc
WORKDIR /var/www

# Cài đặt các dependencies cần thiết
RUN apt-get update && apt-get install -y \
    libpng-dev \
    zip \
    unzip \
    git \
    curl

# Cài đặt Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
