version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dormitory_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dormitory-net

  auth-service:
    build:
      context: ./services/auth-service
    restart: always
    depends_on:
      - mysql
    ports:
      - "8001:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dormitory_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./services/auth-service:/var/www/html
    networks:
      - dormitory-net

  notification-service:
    build:
      context: ./services/notification-service
    restart: always
    depends_on:
      - mysql
    ports:
      - "8002:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dormitory_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./services/notification-service:/var/www/html
    networks:
      - dormitory-net

  payment-service:
    build:
      context: ./services/payment-service
    restart: always
    depends_on:
      - mysql
    ports:
      - "8003:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dormitory_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./services/payment-service:/var/www/html
    networks:
      - dormitory-net

  room-service:
    build:
      context: ./services/room-service
    restart: always
    depends_on:
      - mysql
    ports:
      - "8004:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dormitory_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./services/room-service:/var/www/html
    networks:
      - dormitory-net

  student-service:
    build:
      context: ./services/student-service
    restart: always
    depends_on:
      - mysql
    ports:
      - "8005:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dormitory_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./services/student-service:/var/www/html
    networks:
      - dormitory-net

  api-gateway:
    build:
      context: ./api-gateway
    restart: always
    depends_on:
      - auth-service
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/var/www/html
    networks:
      - dormitory-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Đảm bảo Dockerfile tồn tại trong thư mục frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - dormitory-net

volumes:
  mysql_data:

networks:
  dormitory-net:
