services:
  frontend:
    build:
      context: ./frontend
    restart: always
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      TZ: Asia/Ho_Chi_Minh
    networks:
      - dormitory-net
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
        npm start

networks:
  dormitory-net:
    external: true
